"use client";

import { useRef, useState } from "react";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Explanation } from "@/lib/analytics/ai-explainer";
import type { AnalyticsRequestBody } from "@/lib/analytics/request-schemas";
import { fetchExplanation } from "@/lib/client-analytics";

/**
 * Optional AI narrative over the DETERMINISTIC results. On-demand (not automatic
 * — avoids cost/token churn). Degrades gracefully when AI is not configured; the
 * numbers above are always the source of truth.
 */
export function AiSummaryPanel({ company, analytics }: { company: string; analytics: AnalyticsRequestBody }) {
  const [data, setData] = useState<Explanation | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const ctrl = useRef<AbortController | null>(null);

  const generate = () => {
    ctrl.current?.abort();
    const c = new AbortController();
    ctrl.current = c;
    setLoading(true);
    setError(null);
    fetchExplanation(company, { analytics }, c.signal)
      .then((d) => setData(d))
      .catch((e) => e?.name !== "AbortError" && setError(e instanceof Error ? e.message : "Failed"))
      .finally(() => c.signal.aborted || setLoading(false));
  };

  return (
    <div className="rounded-lg border bg-card/50 p-4">
      <div className="flex items-center justify-between">
        <h3 className="flex items-center gap-1.5 text-sm font-semibold">
          <Sparkles className="size-4 text-primary" aria-hidden /> AI summary
          <span className="font-normal text-muted-foreground">(optional)</span>
        </h3>
        <Button variant="outline" size="sm" onClick={generate} disabled={loading}>
          {loading ? "Generating…" : data ? "Regenerate" : "Generate"}
        </Button>
      </div>

      {error ? (
        <p className="mt-2 text-sm text-muted-foreground">{error}</p>
      ) : data ? (
        <div className="mt-2">
          <p className="whitespace-pre-wrap text-sm text-foreground">{data.summary}</p>
          <p className="mt-2 text-[11px] italic text-muted-foreground">{data.disclaimer}</p>
          <p className="mt-1 text-[11px] text-muted-foreground">Generated by {data.mode === "mock" ? "the offline mock explainer" : "Claude"} from the deterministic results above.</p>
        </div>
      ) : (
        <p className="mt-2 text-sm text-muted-foreground">
          Generate a plain-English summary of the deterministic results above. The AI explains the numbers — it never computes or invents them.
        </p>
      )}
    </div>
  );
}
